"use client";
import {useCallback,useState} from "react";
import type {inferRouterOutputs} from "@trpc/server";
import type {AppRouter} from "@/server/api/router";
import type {Target} from "@/server/services/staff";
import {api} from "@/lib/api-client";
import {campusDate,campusTime} from "@/lib/timetable/dates";
import {allPages,Drawer,message,Notice,useRemote} from "./common";
type Announcement=inferRouterOutputs<AppRouter>["announcement"]["listManaged"]["items"][number];
function Editor({record,close,done}:{record:Announcement|null;close:()=>void;done:()=>void}) {
  const [title,setTitle]=useState(record?.title??"");const [body,setBody]=useState(record?.body??"");const [targets,setTargets]=useState<Target[]>(record?.targets??[]);const [busy,setBusy]=useState(false),[error,setError]=useState("");
  const options=useRemote(useCallback(()=>api.announcement.options.query(),[]));
  async function save(){setBusy(true);setError("");try{if(record)await api.announcement.update.mutate({announcementId:record.id,expectedRevision:record.revision,title,body,targets});else await api.announcement.create.mutate({title,body,targets});done();close();}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <Drawer title={record?"Edit Announcement":"Create Announcement"} close={close}><label className="work-label">Title<input maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/></label><fieldset className="work-targets"><legend>Targets</legend><p className="work-muted">CLASS reaches only that class. Multiple targets are combined.</p>{options.error?<Notice text={options.error}/>:!options.value?<p>Loading permitted targets…</p>:options.value.map(o=>{const key=JSON.stringify(o.target),checked=targets.some(t=>JSON.stringify(t)===key);return <label key={key}><input type="checkbox" checked={checked} onChange={()=>setTargets(old=>checked?old.filter(t=>JSON.stringify(t)!==key):[...old,o.target])}/>{o.label}</label>;})}</fieldset><label className="work-label">Content<textarea maxLength={5000} rows={10} value={body} onChange={e=>setBody(e.target.value)}/></label><p className="work-muted">Drafts are private. Published announcements must be withdrawn before replacing their content.</p>{error&&<Notice text={error}/>}<button className="work-button primary" disabled={busy||!title.trim()||!body.trim()||!options.value} onClick={save}>{busy?"Saving…":"Save Draft"}</button></Drawer>;
}
export function AnnouncementManager(){
  const options=useRemote(useCallback(()=>api.announcement.options.query(),[]));
  const targetLabel=(t:Target)=>options.value?.find(o=>JSON.stringify(o.target)===JSON.stringify(t))?.label??`${t.type.toUpperCase()} · unavailable target`;
  const [revision,setRevision]=useState(0),[status,setStatus]=useState<"draft"|"published"|"withdrawn"|undefined>();const [editor,setEditor]=useState<Announcement|null|undefined>();const [confirm,setConfirm]=useState<{record:Announcement;action:"publish"|"withdraw"}|null>(null);const [busy,setBusy]=useState(false),[error,setError]=useState("");
  const result=useRemote(useCallback(()=>allPages(cursor=>api.announcement.listManaged.query({status,cursor,limit:50})),[status]),revision);
  async function change(){if(!confirm)return;setBusy(true);setError("");try{await api.announcement[confirm.action].mutate({announcementId:confirm.record.id,expectedRevision:confirm.record.revision});setConfirm(null);setRevision(n=>n+1);}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <main className="work-main tinted"><header className="work-header"><div><h1>Announcements</h1><p>Manage announcements for your classes.</p></div><button className="work-button primary" onClick={()=>setEditor(null)}>Create Announcement</button><button className="work-button" onClick={()=>setRevision(n=>n+1)}>Refresh</button></header><div className="work-tabs">{([undefined,"draft","published","withdrawn"] as const).map(s=><button key={s??"all"} aria-pressed={status===s} onClick={()=>setStatus(s)}>{s??"All"}</button>)}</div>{error&&<Notice text={error}/>} {result.error?<Notice text={result.error}/>:!result.value?<p role="status">Loading announcements…</p>:<div className="work-table-wrap"><table className="work-table"><thead><tr><th>Title</th><th>Scope</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{result.value.map(a=><tr key={a.id}><td><strong>{a.title}</strong><small className="work-preview">{a.body}</small></td><td>{a.targets.map(targetLabel).join(", ")||"No targets"}</td><td><span className={`work-badge ${a.status}`}>{a.status}</span></td><td>{campusDate(a.updatedAt)}</td><td>{a.status==="draft"?<><button className="work-link" onClick={()=>setEditor(a)}>Edit</button><button className="work-link" onClick={()=>{setError("");setConfirm({record:a,action:"publish"});}}>Publish</button></>:a.status==="published"?<button className="work-link" onClick={()=>{setError("");setConfirm({record:a,action:"withdraw"});}}>Withdraw</button>:"Withdrawn"}</td></tr>)}</tbody></table>{!result.value.length&&<p className="p-6">No announcements.</p>}</div>}{editor!==undefined&&<Editor record={editor} close={()=>setEditor(undefined)} done={()=>setRevision(n=>n+1)}/>} {confirm&&<Drawer title={`${confirm.action==="publish"?"Publish":"Withdraw"} announcement`} close={()=>setConfirm(null)}><p className="my-6">{confirm.record.title}</p><p>{confirm.record.targets.map(targetLabel).join(", ")}</p><p className="work-muted">{confirm.action==="publish"?"Only students in the selected targets will be able to read it.":"This announcement will no longer be visible as an active announcement."}</p>{error&&<Notice text={error}/>}<button className="work-button primary" disabled={busy} onClick={change}>{busy?"Saving…":"Confirm"}</button></Drawer>}</main>;
}
export function StudentAnnouncements(){
  const [revision,setRevision]=useState(0),[selected,setSelected]=useState<string|null>(null);const result=useRemote(useCallback(()=>allPages(cursor=>api.announcement.listVisible.query({cursor,limit:50})),[]),revision);
  const detail=useRemote(useCallback(()=>selected?api.announcement.getVisible.query({announcementId:selected}):Promise.resolve(null),[selected]),revision);
  return <main className="work-main"><header className="work-header"><h1>Announcements</h1><button className="work-button" onClick={()=>setRevision(n=>n+1)}>Refresh</button></header>{result.error?<Notice text={result.error}/>:!result.value?<p role="status">Loading announcements…</p>:!result.value.length?<p>No announcements for you.</p>:<div className="work-table-wrap"><table className="work-table"><thead><tr><th>Message</th><th>Sender</th><th>Date · Sydney</th></tr></thead><tbody>{result.value.map(a=><tr key={a.id}><td><button className="work-link" onClick={()=>setSelected(a.id)}>{a.title}</button></td><td>{a.author.displayName}</td><td>{campusDate(a.publishedAt)} {campusTime(a.publishedAt)}</td></tr>)}</tbody></table></div>}{selected&&<Drawer title="Announcement" close={()=>setSelected(null)}>{detail.error?<Notice text={detail.error}/>:!detail.value?<p role="status">Loading…</p>:<><h2 className="my-6 text-xl font-semibold">{detail.value.title}</h2><p className="work-muted">{detail.value.author.displayName}</p><p className="whitespace-pre-wrap break-words">{detail.value.body}</p></>}</Drawer>}</main>;
}
