"use client";
import {useCallback,useState} from "react";
import Link from "next/link";
import {Temporal} from "@js-temporal/polyfill";
import type {inferRouterOutputs} from "@trpc/server";
import type {AppRouter} from "@/server/api/router";
import {api} from "@/lib/api-client";
import {campusToday,campusDate,campusTime,weekRange,shiftWeek,weekDates} from "@/lib/timetable/dates";
import {allPages,Drawer,message,Notice,useRemote} from "./common";
type Share=inferRouterOutputs<AppRouter>["share"]["create"];
const fullFields=["course","classType","startAt","endAt","location"] as const,availability=["startAt","endAt"] as const;
const status=(s:Share)=>s.revokedAt?"Revoked":Date.parse(s.expiresAt)<=Date.now()?"Expired":"Active";
function CreateShare({close,done}:{close:()=>void;done:(s:Share)=>void}){
 const [recipientId,setRecipient]=useState(''),[full,setFull]=useState(false),[date,setDate]=useState(campusToday),[days,setDays]=useState(7),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const recipients=useRemote(useCallback(()=>api.share.recipients.query(),[]));
 async function create(){setBusy(true);setError('');try{const s=await api.share.create.mutate({recipientId,...weekRange(date),allowedFields:full?[...fullFields]:[...availability],expiresAt:new Date(Date.now()+days*86400000).toISOString(),consent:true});done(s);}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <Drawer title="Create Share" close={close}><fieldset className="work-targets"><legend>What to share</legend><label><input type="radio" name="scope" checked={full} onChange={()=>setFull(true)}/>Full Timetable</label><small>Course names, class types, times and locations.</small><label><input type="radio" name="scope" checked={!full} onChange={()=>setFull(false)}/>Availability Only</label><small>Only busy times. No course names or locations.</small></fieldset><label className="work-label">Share with<select value={recipientId} onChange={e=>setRecipient(e.target.value)}><option value="">Select an approved recipient</option>{recipients.value?.map(r=><option key={r.id} value={r.id}>{r.displayName}</option>)}</select></label>{recipients.error&&<Notice text={recipients.error}/>}<label className="work-label">Week to share · Sydney<input type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label><div className="work-tabs"><button onClick={()=>setDate(shiftWeek(date,-1))}>Previous week</button><button onClick={()=>setDate(shiftWeek(date,1))}>Next week</button></div><label className="work-label">Expires after<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 days</option><option value={30}>30 days</option></select></label><label className="share-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I agree to share these fields for this week with this recipient until expiry or revocation. The recipient must sign in. Revoking stops future access but cannot erase copies already made.</label>{error&&<Notice text={error}/>}<button className="work-button primary" disabled={busy||!consent||!recipientId} onClick={create}>{busy?'Creating…':'Create Share'}</button></Drawer>;
}
export function Shares(){
 const [revision,setRevision]=useState(0),[direction,setDirection]=useState<'sent'|'received'>('sent'),[creating,setCreating]=useState(false),[created,setCreated]=useState<Share|null>(null),[revoke,setRevoke]=useState<Share|null>(null),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const result=useRemote(useCallback(()=>allPages(cursor=>api.share.list.query({direction,cursor,limit:50})),[direction]),revision);
 async function confirm(){if(!revoke)return;setBusy(true);try{await api.share.revoke.mutate({shareId:revoke.id});setRevoke(null);setRevision(n=>n+1);setNotice('Share revoked. Future reads are no longer authorized.');}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function copy(s:Share){try{await navigator.clipboard.writeText(`${window.location.origin}/student/compare?share=${s.id}`);setNotice('Link copied. Only the signed-in recipient can use it.');}catch{setNotice('Copy unavailable. Select the link text and copy it.');}}
 return <main className="work-main"><header className="work-header"><div><h1>Shared Timetables</h1><p>Share your timetable with others.</p></div><button className="work-button" onClick={()=>setCreating(true)}>+ Create Share</button><button className="work-button" onClick={()=>setRevision(n=>n+1)}>Refresh</button></header><div className="work-tabs"><button aria-pressed={direction==='sent'} onClick={()=>setDirection('sent')}>Sent</button><button aria-pressed={direction==='received'} onClick={()=>setDirection('received')}>Received</button></div>{notice&&<p role="status" className="work-notice">{notice}</p>}{error&&<Notice text={error}/>} {result.error?<Notice text={result.error}/>:!result.value?<p role="status">Loading shares…</p>:!result.value.length?<p>No shares yet.</p>:result.value.map(s=><article key={s.id} className={`share-row ${status(s)==='Active'?'active':''}`}><div><strong>{s.allowedFields.includes('course')?'Full Timetable':'Availability Only'}</strong><p>{direction==='sent'?'Recipient':'Owner'}: {direction==='sent'?s.recipientId:s.ownerId}</p><small>{campusDate(s.from)} – {campusDate(new Date(Date.parse(s.to)-1).toISOString())} · Expires {campusDate(s.expiresAt)} {campusTime(s.expiresAt)}</small></div><span className="work-badge">{status(s)}</span>{direction==='sent'?<><button className="work-link" onClick={()=>copy(s)}>Copy link</button>{!s.revokedAt&&<button className="work-link" onClick={()=>{setError('');setRevoke(s);}}>Revoke</button>}</>:<Link className="work-link" href={`/student/compare?share=${s.id}`}>Compare</Link>}</article>)}{creating&&<CreateShare close={()=>setCreating(false)} done={s=>{setCreating(false);setCreated(s);setRevision(n=>n+1);}}/>}{created&&<Drawer title="Share created" close={()=>setCreated(null)}><p className="my-6">Only your selected recipient can use this link after signing in.</p><label className="work-label">Share link<input readOnly value={`${typeof window==='undefined'?'':window.location.origin}/student/compare?share=${created.id}`}/></label><button className="work-button primary" onClick={()=>copy(created)}>Copy link</button>{notice&&<p role="status">{notice}</p>}</Drawer>}{revoke&&<Drawer title="Revoke share?" close={()=>setRevoke(null)}><p className="my-6">This stops the recipient from reading or comparing this share again.</p>{error&&<Notice text={error}/>}<button className="work-button primary" onClick={confirm} disabled={busy}>{busy?'Revoking…':'Confirm revoke'}</button></Drawer>}</main>;
}
function parseShare(value:string){try{const url=new URL(value,window.location.origin);if(url.origin!==window.location.origin||url.pathname!=='/student/compare')return null;const id=url.searchParams.get('share');return id&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)?id:null;}catch{return null;}}
export function Compare({initialShare,initialDate}:{initialShare?:string;initialDate?:string}){
 const [value,setValue]=useState(initialShare?`/student/compare?share=${initialShare}`:''),[id,setId]=useState(initialShare??''),[date,setDate]=useState(initialDate??campusToday()),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const result=useRemote(useCallback(()=>id?allPages(cursor=>api.timetable.compare.query({shareId:id,...weekRange(date),cursor,limit:50})):Promise.resolve(null),[id,date]),revision);
 const compare=()=>{const parsed=parseShare(value);if(!parsed){setId('');setError('Invalid link. Use a timetable link shared with your account.');}else{setError('');setId(parsed);setRevision(n=>n+1);}};
 return <main className="work-main"><header className="work-header"><h1>Compare Timetables</h1></header><form className="compare-form" onSubmit={e=>{e.preventDefault();compare();}}><label className="work-label">Shared timetable link<input value={value} onChange={e=>setValue(e.target.value)} placeholder="Paste a shared timetable link…"/></label><button className="work-button primary">Compare</button></form>{error&&<Notice text={error}/>} {!id?<div className="compare-empty"><h2>Compare your week</h2><p>Paste a link shared with you to see both timetables side by side.</p></div>:<><div className="work-header"><button className="work-button" onClick={()=>setDate(shiftWeek(date,-1))} aria-label="Previous week">‹</button><button className="work-button" onClick={()=>setDate(shiftWeek(date,1))} aria-label="Next week">›</button><strong>Week of {weekDates(date)[0]} · Australia/Sydney</strong><label className="work-label">Choose week<input type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label><button className="work-button" onClick={()=>setRevision(n=>n+1)}>Refresh</button></div>{result.error?<Notice text={`${result.error} The link may be unavailable, expired, revoked, or outside its shared week.`}/>:!result.value?<p role="status">Loading both timetables…</p>:!result.value.length?<p>No classes in this shared week.</p>:<div className="compare-grid">{weekDates(date).map(day=><section className="compare-day" key={day}><h2>{Temporal.PlainDate.from(day).toLocaleString('en-AU',{weekday:'short',day:'numeric',month:'short'})}</h2><div className="compare-sides">{(['self','shared'] as const).map(side=><div key={side}><h3>{side==='self'?'You':'Shared'}</h3>{result.value?.filter(r=>r.side===side&&campusDate(r.entry.startAt)===day).map(r=><article className={`compare-card ${side}`} key={`${side}-${r.entry.id}`}><strong>{r.entry.course?.code??'Busy'}</strong><small>{campusTime(r.entry.startAt)} – {campusTime(r.entry.endAt)}</small>{r.entry.location&&<small>{r.entry.location}</small>}</article>)}</div>)}</div></section>)}</div>}</>}</main>;
}
