"use client";
import {useCallback,useState} from "react";
import {api} from "@/lib/api-client";
import {campusToday,weekRange,campusTime,campusDate} from "@/lib/timetable/dates";
import type {Principal} from "@/server/auth/authorization";
import type {TimetableItem} from "@/server/services/timetable";
import {allPages,Drawer,message,Notice,useRemote} from "./common";
function NotesEditor({item,close,saved}:{item:TimetableItem;close:()=>void;saved:()=>void}) {
  const [noteId,setNoteId]=useState("");const note=item.supplements.find(n=>n.id===noteId);
  const [content,setContent]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function save(){setBusy(true);setError("");try{await api.supplement.save.mutate({entryId:item.id,content,...(note?{supplementId:note.id,expectedRevision:note.revision}:{})});saved();close();}catch(e){setError(message(e));}finally{setBusy(false);}}
  return <Drawer title={`${item.course.code} · Supplementary information`} close={close}><p className="work-muted">{campusDate(item.startAt)} · {campusTime(item.startAt)} · {item.location??"Location unknown"}</p><p className="work-muted">Supplementary information is shown separately from source data. Class times, locations and capacity are read-only.</p><label className="work-label">Note<select value={noteId} onChange={e=>{setNoteId(e.target.value);setContent(item.supplements.find(n=>n.id===e.target.value)?.content??"");setError("");}}><option value="">Create a new note</option>{item.supplements.map(n=><option key={n.id} value={n.id}>{n.content.slice(0,50)} · revision {n.revision}</option>)}</select></label><label className="work-label">Supplementary content<textarea maxLength={5000} rows={9} value={content} onChange={e=>setContent(e.target.value)}/></label>{error&&<><Notice text={error}/><button className="work-button" onClick={saved}>Reload timetable (keeps this text)</button></>}<button className="work-button primary" disabled={busy||!content.trim()} onClick={save}>{busy?"Saving…":"Save supplementary information"}</button></Drawer>;
}
export function StaffWorkspace({principal}:{principal:Principal}) {
  const [date,setDate]=useState(campusToday);const [revision,setRevision]=useState(0);const [selected,setSelected]=useState<TimetableItem|null>(null);const [notice,setNotice]=useState("");
  const load=useCallback(()=>allPages(cursor=>api.staff.listEntries.query({...weekRange(date),cursor,limit:50})),[date]);const result=useRemote(load,revision);
  return <main className="work-main"><header className="work-header"><div><h1>Staff Workspace</h1><p>Manage the courses and classes assigned to you.</p></div><label className="work-label">Week of<input type="date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label><button className="work-button" onClick={()=>setRevision(n=>n+1)}>Refresh</button></header>{notice&&<p role="status" className="work-notice">{notice}</p>}{result.error?<Notice text={result.error}/>:!result.value?<p role="status">Loading assigned classes…</p>:!result.value.length?<p>No classes in this week.</p>:<div className="work-table-wrap"><table className="work-table"><thead><tr><th>Course</th><th>Class</th><th>Time · Sydney</th><th>Location</th><th>Available places</th><th>Actions</th></tr></thead><tbody>{result.value.map(item=><tr key={item.id}><td><strong>{item.course.code}</strong><small>{item.course.name}</small></td><td>{item.classType}</td><td>{campusDate(item.startAt)}<small>{campusTime(item.startAt)} – {campusTime(item.endAt)}</small></td><td>{item.location??"Unknown"}</td><td>{item.capacity?.available??"Unknown"}</td><td>{principal.grants.some(g=>g.permission==="supplement.write"&&g.courseId===item.course.id)&&<button className="work-link" onClick={()=>setSelected(item)}>Edit supplement</button>}</td></tr>)}</tbody></table></div>}{selected&&<NotesEditor key={selected.id} item={selected} close={()=>setSelected(null)} saved={()=>{setRevision(n=>n+1);setNotice("Timetable reloaded. Close and reopen a note to use its latest revision.");}}/>}</main>;
}
