import assert from 'node:assert/strict';
import {before,after,describe,it} from 'node:test';
import {randomBytes} from 'node:crypto';
import {eq,and} from 'drizzle-orm';
import {testDatabase} from './test-database';
import {seedFixtures,fixtureUsers} from '../src/server/db/seed';
import {createAuth,authRequest,type AppAuth} from '../src/server/auth/auth';
import {provisionTestAccounts} from '../src/server/auth/provision-test-accounts';
import {trpcRequest} from '../src/server/api/handler';
import {shares,shareRecipients,studentClasses,userRoles} from '../src/server/db/schema';
const origin='http://127.0.0.1:3000',range={from:'2026-09-20T00:00:00Z',to:'2026-09-23T00:00:00Z'};
describe('Recipient-bound sharing and revocation',{concurrency:false},()=>{
 let d:Awaited<ReturnType<typeof testDatabase>>,auth:AppAuth;const cookies:Record<string,string>={};
 async function rpc(path:string,input:unknown,id='test-student-a',write=false){const r=await trpcRequest(new Request(`${origin}/api/trpc/${path}${write?'':`?input=${encodeURIComponent(JSON.stringify(input))}`}`,{method:write?'POST':'GET',headers:{Cookie:cookies[id]??'',Origin:origin,'Content-Type':'application/json'},...(write?{body:JSON.stringify(input)}:{})}),{db:d.db,auth});return{status:r.status,body:await r.json()};}
 const input=(full=false)=>({...range,recipientId:'test-student-b',allowedFields:full?['course','classType','startAt','endAt','location']:['startAt','endAt'],expiresAt:new Date(Date.now()+7*86400000).toISOString(),consent:true});
 const create=async(full=false)=>(await rpc('share.create',input(full),undefined,true)).body.result.data;
 const read=(id:string,extra:object={},who='test-student-b')=>rpc('share.read',{...range,shareId:id,...extra},who);
 before(async()=>{d=await testDatabase();await seedFixtures(d.db);auth=createAuth(d.db,{secret:randomBytes(48).toString('hex'),baseURL:origin});const password=randomBytes(24).toString('hex');await provisionTestAccounts(d.db,auth,Object.fromEntries(fixtureUsers.map(p=>[p.id,password])));for(const p of fixtureUsers){const r=await authRequest(auth,new Request(`${origin}/api/auth/sign-in/email`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({email:p.email,password})}));cookies[p.id]=r.headers.getSetCookie().map(c=>c.split(';')[0]).join('; ');}});after(async()=>{await d?.close();});
 it('requires consent, a permitted recipient, finite expiry and an exact field whitelist',async()=>{for(const change of [{consent:false},{recipientId:'test-student-empty'},{recipientId:'test-student-a'},{expiresAt:new Date(Date.now()-1000).toISOString()},{expiresAt:new Date(Date.now()+31*86400000).toISOString()},{allowedFields:['startAt','endAt','supplements']},{ownerId:'test-student-b'}])assert.notEqual((await rpc('share.create',{...input(),...change},undefined,true)).status,200);assert.equal((await rpc('share.create',input(),'test-teacher',true)).status,403);});
 it('B reads only busy times; C, the owner, and unauthenticated requests are refused',async()=>{const s=await create();const r=await read(s.id);assert.equal(r.status,200);assert.equal(r.body.result.data.items.length,2);for(const item of r.body.result.data.items)assert.deepEqual(Object.keys(item).sort(),['endAt','id','startAt']);assert.equal((await read(s.id,{},'test-student-empty')).status,404);assert.equal((await read(s.id,{},'test-student-a')).status,404);assert.equal((await read(s.id,{},'anonymous')).status,401);});
 it('full shares expose only approved fields and limit all reads to granted intervals',async()=>{const s=await create(true),r=await read(s.id);assert.deepEqual(Object.keys(r.body.result.data.items[0]).sort(),['classType','course','endAt','id','location','startAt']);assert.equal((await read(s.id,{from:'2026-09-19T00:00:00Z'})).status,403);const clipped=await read(s.id,{from:'2026-09-20T23:30:00Z',to:'2026-09-21T00:30:00Z'});assert.equal(clipped.body.result.data.items[0].startAt,'2026-09-20T23:30:00.000Z');});
 it('compares both sides in stable order across all pages',async()=>{const s=await create();const seen:unknown[]=[];let cursor:undefined|string;do{const r=await rpc('timetable.compare',{shareId:s.id,...range,limit:1,cursor},'test-student-b');assert.equal(r.status,200);seen.push(...r.body.result.data.items);cursor=r.body.result.data.nextCursor??undefined;}while(cursor);assert.equal(seen.length,3);const entries=seen as {side:string;entry:Record<string,unknown>}[];assert.equal(entries.filter(r=>r.side==='self').length,1);assert.ok(entries.filter(r=>r.side==='shared').every(r=>!('course' in r.entry)));assert.equal(new Set(entries.map(r=>`${r.side}-${r.entry.id}`)).size,3);});
 it('binds signed pagination to viewer, share, range and query type',async()=>{const a=await create(),b=await create();const cursor=(await read(a.id,{limit:1})).body.result.data.nextCursor;assert.equal((await read(b.id,{cursor})).status,400);assert.equal((await read(a.id,{cursor:cursor+'x'})).status,400);assert.equal((await rpc('timetable.compare',{shareId:a.id,...range,cursor},'test-student-b')).status,400);});
 it('revoke is owner-only and idempotent; pagination stops immediately',async()=>{const s=await create(),cursor=(await read(s.id,{limit:1})).body.result.data.nextCursor;assert.equal((await rpc('share.revoke',{shareId:s.id},'test-student-b',true)).status,404);const first=await rpc('share.revoke',{shareId:s.id},undefined,true),second=await rpc('share.revoke',{shareId:s.id},undefined,true);assert.deepEqual(first.body.result.data,second.body.result.data);assert.equal((await read(s.id,{cursor})).status,404);assert.equal((await rpc('timetable.compare',{shareId:s.id,...range},'test-student-b')).status,404);});
 it('expiry and approved-recipient withdrawal invalidate reads',async()=>{const s=await create();await d.db.update(shares).set({consentedAt:new Date(Date.now()-86400000),expiresAt:new Date(Date.now()-1000)}).where(eq(shares.id,s.id));assert.equal((await read(s.id)).status,404);const a=await create();await d.db.update(shareRecipients).set({active:false}).where(eq(shareRecipients.ownerId,'test-student-a'));assert.equal((await read(a.id)).status,404);await d.db.update(shareRecipients).set({active:true}).where(eq(shareRecipients.ownerId,'test-student-a'));});
 it('lists only the current participant records',async()=>{const r=await rpc('share.list',{direction:'sent'});assert.ok(r.body.result.data.items.every((s:{ownerId:string})=>s.ownerId==='test-student-a'));assert.equal((await rpc('share.list',{direction:'received'},'test-student-empty')).body.result.data.items.length,0);});
 it('class and student-role revocation remove shared data',async()=>{const s=await create();await d.db.update(studentClasses).set({status:'inactive'}).where(eq(studentClasses.userId,'test-student-a'));assert.equal((await read(s.id)).body.result.data.items.length,0);await d.db.delete(userRoles).where(and(eq(userRoles.userId,'test-student-a'),eq(userRoles.role,'student')));assert.equal((await read(s.id)).status,404);});
});
